Update requirements.txt for newer Python versions
I cloned this and attempted to run in 3.11 on an M2
It had an error:

> AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

Turns out this isn't your code, but comes from cherrypy